"""Initial migration.

Revision ID: 6a4afa6caaa9
Revises: 
Create Date: 2021-09-11 18:54:12.828004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4afa6caaa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('border',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LIMIT', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('border')
    op.drop_table('country')
    # ### end Alembic commands ###
