"""Add uniqueness

Revision ID: c67f7bf0f182
Revises: 6a4afa6caaa9
Create Date: 2021-09-13 18:44:44.240745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67f7bf0f182'
down_revision = '6a4afa6caaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'iso',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'country', ['iso'])
    op.create_unique_constraint(None, 'country', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'iso',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
